openapi: 3.0.0

info:
  # title: API Gateway用にデプロイ時に自動で書き換える。設定したい場合は、openapi/env.confで設定
  # description: API Gateway用にデプロイ時に自動で書き換える。設定したい場合は、openapi/env.confで設定
  title: NEXT-STARTUP-TITLE
  description: NEXT-STARTUP-DESC
  contact:
    name: 'API Support'
    url: https://github.com/yokohama/next-startup-mock
  version: 1.0.1

# ISSUE: 16
servers:
  - url: http://localhost:3000

security:
  - bearerAuth: []

paths:
  /users:
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
      - CORS
      responses:
        200:
          description: Default response for CORS method
          headers: 
            Access-Control-Allow-Origin:  
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Methods: 
              $ref: '#/components/headers/Access-Control-Allow-Methods'
            Access-Control-Allow-Headers: 
              $ref: '#/components/headers/Access-Control-Allow-Headers'
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            { "statusCode" : 200 }
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
              method.response.header.Access-Control-Allow-Methods: '''*'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
            responseTemplates:
              application/json: |
                {}
    get:
      tags:
        - users
      summary: Get all users.
      description: Returns an array of User model.
      parameters: []
      responses:
        '200':
          description: A Json array of User model.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                example:
                  - id: 1
                    name: Hoge Moge
                  - id: 2
                    name: Foo Bar
      x-amazon-apigateway-integration:
        type: "http_proxy" 
        httpMethod: "GET" 
        connectionType: "VPC_LINK" 
        connectionId: "{NEXT-STARTUP-VPC-LINK-ID}" 
        uri: "http://{NEXT-STARTUP-LB-URI}/users"

components:
  headers:
    Access-Control-Allow-Origin:
      schema:
        type: string
    Access-Control-Allow-Methods:
      schema:
        type: string
    Access-Control-Allow-Headers:
      schema:
        type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
